### ISSUE TITLE
Add VINCI: DaVinci Token

### ISSUE THREAD

**Issue by BrunoMarshall** [LootSwap/lootswap-default-token-list#1]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xb8e0497018c991e86311b64efd9d57b06aedbbae
Token Name (from contract): DaVinci Token
Token Decimals (from contract): 18
Token Symbol (from contract): VINCI
Uniswap V2 Pair Address of Token: 

Link to the official homepage of token: https://davinci.gallery/
Link to CoinMarketCap or CoinGecko page of token:

**Comment by defiproject** [comment]
Thank you @BrunoMarshall will merge this in as soon as the PR conflicts get resolved

**Comment by defiproject** [comment]
Since i had to update the token list , i went ahead and added your Vinci to the list https://github.com/LootSwap/lootswap-default-token-list/commit/9966c96d4ba418b5d4b09da2e3af1b7b545c0706#diff-25aa356105a526ec81c4af183c06546c233a536c28f00d1111dd686a2aae70e1R280 

please reopen the issue if you feel like I made a mistake.
